name: clang-tidy-review

on:
  pull_request:

jobs:
  clang-tidy-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SDL windowing deps (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              build-essential cmake ninja-build pkg-config gcc g++ clang git python3 python3-pip \
              libasound2-dev libjack-jackd2-dev libpulse-dev \
              xorg-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
              libxkbcommon-dev wayland-protocols libwayland-dev \
              libdrm-dev mesa-common-dev mesa-utils

      - name: Configure (CMake)
        run: |
          cmake -S ${{ github.workspace }} 
              -B build
              -G Ninja
              -DCMAKE_CXX_COMPILER=clang++
              -DCMAKE_C_COMPILER=clang
              -DCMAKE_BUILD_TYPE=Release
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy-review
        uses: ZedThree/clang-tidy-review@v0.21.0
        id: review
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          build_dir: build
